version: '3'
services:
  backend:
    image: smcebi:dev
    build: .
    env_file: .env
    ports:
      - "${DJANGO_PORT:-8000}:8000"
    volumes:
      - ./src:/code
      - ./venv/lib/python3.5/site-packages/leaflet:/usr/local/lib/python3.6/site-packages/leaflet

  postgres:
    image: mdillon/postgis
    env_file: .env
    labels:
      - "traefik.enable=false"
    ports:
      - 5555:5432

  pgadmin:
    image: fenglc/pgadmin4
    env_file: .env
    ports:
      - 5050:5050
