# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 22:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('search', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
