# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 20:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('degree', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('roomid', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
