# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='roomid',
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
