# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 19:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LowerGroundFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
            ],
        ),
    ]
